### PR TITLE
Problem with imports in python 3.4 fix

### PR DESCRIPTION
**Pull request by kennedyshead**
I had problem where the imports did not work in python 3.4 installed with pip

### CODE REVIEW

**Comment by bjarneo** [comment]
Awesome. Thank you! Before I merge, did you test it in python 2.7 also?

**Comment by kennedyshead** [comment]
Yes, works like a charm

**Comment by bjarneo** [comment]
Great. Thanks again :+1:

**Comment by bjarneo** [comment]
Tested in python 2.7 now. Won't work.

Traceback (most recent call last):
  File "cli.py", line 2, in <module>
    from .strategy import get_pytify_class_by_platform
ValueError: Attempted relative import in non-package

**Pull request merged**
