### PR TITLE
Add logo on README

### PR DESCRIPTION
**Pull request by theodorosploumis**

### CODE REVIEW

**Comment by theodorosploumis** [comment]
Let's close this. I was doing the same thing right now! :-)

**Comment by bjarneo** [comment]
Your solution might look better though. With the aligning :)

**Comment by bjarneo** [comment]
Do you want to solve the conflict, and then we can merge this PR?

**Comment by theodorosploumis** [comment]
It's OK to resolve it. I am not interested on the commits to be honest.

**Pull request closed without merging**
