### PR TITLE
Added absolute import for python 2 and 3.5 compatibility.

### PR DESCRIPTION
**Pull request by wohlfea**

### CODE REVIEW

**Comment by bjarneo** [comment]
Thank you very much. Publishing to pypi soon.

:+1:

**Comment by bjarneo** [comment]
Pypi atm: Server response (500): Internal Server Error

**Comment by bjarneo** [comment]
@wohlfea If you try to install newest pytify from pip and run it with python 3.5, do you manage to start songs?

**Comment by bjarneo** [comment]
Nevermind. Managed to get it work if I set the alias to python3, not python3.5 (it used version 3.51 with alias python3).

**Comment by wohlfea** [comment]
Cool!  Glad it's fixed.  A nice project you have here!

**Comment by bjarneo** [comment]
Thank you :)

**Pull request merged**
