### PR TITLE
Upgrade Pytify to support prompt_toolkit v2

### PR DESCRIPTION
**Pull request by bharath-123**
This pull request adds support for prompt_toolkit v2 which introduced a lot of breaking changes which rendered Pytify useless. 

This change is split into 3 commits. Brief summary of each commit:
(i) add support in setup.py to requirements.txt for install_requires.
(ii) Add support for prompt_toolkit v2 (The change we have all been waiting for!)
(iii) Make prompt_toolkit v2 (2.0.9) default for Pytify.

Each commit has a more a detailed description.

### CODE REVIEW

**Comment by bharath-123** [comment]
It would be great if some more testing could be done!

**Comment by bjarneo** [comment]
This is awesome. I will test it tomorrow morning.

**Comment by bharath-123** [comment]
Thanks! I ll do testing of my own in the meantime!

**Review by bjarneo — APPROVED** [review]
Looks good to me. I appreciate the refactoring as well. :)

**Comment by bjarneo** [comment]
@bharath-123 Tested it locally as well. Works perfectly fine. Do you want me to merge?

**Review by bjarneo — CHANGES_REQUESTED** [review]
I actually have to request a feedback......you have to add yourself to the contribution section ;)
https://github.com/bjarneo/Pytify#contributors

**Comment by bharath-123** [comment]
I think its fine to merge :) I ll be sticking around if in case anything breaks! I also make the changes required. But I ll do that as a seperate PR?

**Comment by bharath-123** [comment]
Thanks for reviewing :)

**Comment by bharath-123** [comment]
Ok I don't think I need to add as a seperate PR. I ll just push the changes to my branch!

**Comment by bharath-123** [comment]
My first open source work was with the Linux Kernel. Their mailing list approach is completely different from Github :) So I am really not used to github!

**Comment by bjarneo** [comment]
> My first open source work was with the Linux Kernel. Their mailing list approach is completely different from Github :) So I am really not used to github!

Hopefully the github flow is a lot more simplified? (Cool that you contributed to the linux kernel btw)

**Review by bjarneo — APPROVED** [review]

**Comment by bharath-123** [comment]
> > My first open source work was with the Linux Kernel. Their mailing list approach is completely different from Github :) So I am really not used to github!
> 
> Hopefully the github flow is a lot more simplified? (Cool that you contributed to the linux kernel btw)

I will admit that the mailing lists approach is really simple and neater to review. Less GUI is good sometimes :) But Github is wayy better than Gerrit. I think contributing to the kernel helped me a lot.  There are really strict rules on code in the kernel. I am now used to writing detailed commit logs which include motivation of the commit, changes of the commit.

**Comment by bharath-123** [comment]
Thanks for the merge!

**Pull request merged**
